services:
  - type: web
    name: ai-resume-matcher
    env: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python -m spacy download en_core_web_sm
    startCommand: python run.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: ai-resume-db
          property: connectionString
      - key: OPENAI_API_KEY
        sync: false
    healthCheckPath: /
    
databases:
  - name: ai-resume-db
    plan: free
